# Generated by Django 5.2.10 on 2026-02-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_products_updated_at_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
